export const COUNTRY_CODES = [
  { code: "+61", flag: "🇦🇺", name: "Australia" },
  { code: "+32", flag: "🇧🇪", name: "Belgium" },
  { code: "+591", flag: "🇧🇴", name: "Bolivia" },
  { code: "+55", flag: "🇧🇷", name: "Brazil" },
  { code: "+56", flag: "🇨🇱", name: "Chile" },
  { code: "+86", flag: "🇨🇳", name: "China" },
  { code: "+57", flag: "🇨🇴", name: "Colombia" },
  { code: "+506", flag: "🇨🇷", name: "Costa Rica" },
  { code: "+593", flag: "🇪🇨", name: "Ecuador" },
  { code: "+503", flag: "🇸🇻", name: "El Salvador" },
  { code: "+34", flag: "🇪🇸", name: "Spain" },
  { code: "+63", flag: "🇵🇭", name: "Philippines" },
  { code: "+33", flag: "🇫🇷", name: "France" },
  { code: "+358", flag: "🇫🇮", name: "Finland" },
  { code: "+49", flag: "🇩🇪", name: "Germany" },
  { code: "+502", flag: "🇬🇹", name: "Guatemala" },
  { code: "+44", flag: "🇬🇧", name: "United Kingdom" },
  { code: "+504", flag: "🇭🇳", name: "Honduras" },
  { code: "+91", flag: "🇮🇳", name: "India" },
  { code: "+39", flag: "🇮🇹", name: "Italy" },
  { code: "+81", flag: "🇯🇵", name: "Japan" },
  { code: "+82", flag: "🇰🇷", name: "South Korea" },
  { code: "+505", flag: "🇳🇮", name: "Nicaragua" },
  { code: "+47", flag: "🇳🇴", name: "Norway" },
  { code: "+64", flag: "🇳🇿", name: "New Zealand" },
  { code: "+507", flag: "🇵🇦", name: "Panama" },
  { code: "+595", flag: "🇵🇾", name: "Paraguay" },
  { code: "+51", flag: "🇵🇪", name: "Peru" },
  { code: "+52", flag: "🇲🇽", name: "Mexico" },
  { code: "+351", flag: "🇵🇹", name: "Portugal" },
  { code: "+1", flag: "🇺🇸", name: "United States" },
  { code: "+598", flag: "🇺🇾", name: "Uruguay" },
  { code: "+58", flag: "🇻🇪", name: "Venezuela" },
  { code: "+41", flag: "🇨🇭", name: "Switzerland" },
  { code: "+46", flag: "🇸🇪", name: "Sweden" },
];
